# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/test_spec/user_const.xdc

# Block Designs: bd/red_pitaya_bd/red_pitaya_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_bd || ORIG_REF_NAME==red_pitaya_bd} -quiet] -quiet

# IP: bd/red_pitaya_bd/ip/red_pitaya_bd_axi_protocol_convert_0_0/red_pitaya_bd_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_bd_axi_protocol_convert_0_0 || ORIG_REF_NAME==red_pitaya_bd_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/red_pitaya_bd/ip/red_pitaya_bd_processing_system7_0_0/red_pitaya_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_bd_processing_system7_0_0 || ORIG_REF_NAME==red_pitaya_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==red_pitaya_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==red_pitaya_bd_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/red_pitaya_bd_ooc.xdc
