# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.cache/wt [current_project]
set_property parent.project_path /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/sysgen [current_project]
update_ip_catalog
set_property ip_output_repo /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/infrastructure/red_pitaya.v
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/red_pitaya_adc/red_pitaya_adc.v
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/sys_block/sys_block_counter.v
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/test_spec/top.v
}
read_vhdl -library xil_defaultlib {
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/asym_bram_tdp.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/axi4_lite/axi4lite_pkg.vhd
  /home/shishir/pythontest/mlib_devel/jasper_library/hdl_sources/axi4_lite/axi4lite_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accum0_snap_ss_bram_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/axi4_lite/axi4lite_slave_logic.vhd
  /home/shishir/pythontest/mlib_devel/jasper_library/hdl_sources/axi4_lite/axi4lite_slave_logic.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accum0_snap_ss_bram_muxdemux.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/ipb_accum0_snap_ss_bram_dp_ram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accum0_snap_ss_bram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accum1_snap_ss_bram_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accum1_snap_ss_bram_muxdemux.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/ipb_accum1_snap_ss_bram_dp_ram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accum1_snap_ss_bram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accumdat_snap_ss_bram_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accumdat_snap_ss_bram_muxdemux.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/ipb_accumdat_snap_ss_bram_dp_ram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_accumdat_snap_ss_bram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_adc_voltage_snap_ss_bram_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_adc_voltage_snap_ss_bram_muxdemux.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/ipb_adc_voltage_snap_ss_bram_dp_ram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_adc_voltage_snap_ss_bram.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_axi4lite_top_ic_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_axi4lite_top_mmap_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_axi4lite_top_ic.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_sw_reg_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_sys_pkg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_sw_reg_muxdemux.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_sw_reg.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_sys_muxdemux.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/xml2vhdl_hdl_output/axi4lite_sys.vhd
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/test_spec/axi4lite_ic_wrapper.vhdl
  /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/imports/utils/cdc_synchroniser.vhd
}
add_files /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/bd/red_pitaya_bd/red_pitaya_bd.bd
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_axi_protocol_convert_0_0/red_pitaya_bd_axi_protocol_convert_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_processing_system7_0_0/red_pitaya_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/red_pitaya_bd_ooc.xdc]

read_ip -quiet /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/ip/test_spec_ip/test_spec_ip.xci
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/constrs/test_spec.xdc]

read_ip -quiet /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/ip/adc_data_fifo/adc_data_fifo.xci
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/adc_data_fifo/adc_data_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/adc_data_fifo/adc_data_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/adc_data_fifo/adc_data_fifo_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/constrs_1/imports/test_spec/user_const.xdc
set_property used_in_implementation false [get_files /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/constrs_1/imports/test_spec/user_const.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
