// MODULE top, AUTOMATICALLY GENERATED BY PYTHON

/**/
`default_nettype wire


module top (
  // red_pitaya: RED_PITAYA
    input [0:0] ADC_CLK_IN_P,
    inout [14:0] DDR_Addr,
    inout DDR_CAS_n,
    inout DDR_CKE,
    inout DDR_CS_n,
    inout DDR_Ck_n,
    inout DDR_Ck_p,
    inout [3:0] DDR_DM,
    inout [31:0] DDR_DQ,
    inout [3:0] DDR_DQS_n,
    inout [3:0] DDR_DQS_p,
    inout DDR_ODT,
    inout [0:0] DDR_RAS_n,
    inout [2:0] DDR_ba,
    inout DDR_reset_n,
    inout DDR_we_n,
    inout FIXED_IO_ddr_vrn,
    inout FIXED_IO_ddr_vrp,
    inout FIXED_IO_ps_clk,
    inout FIXED_IO_ps_porb,
    inout FIXED_IO_ps_srstb,
  // red_pitaya_adc: red_pitaya_adc
    input [9:0] ADC_DATA_IN1,
    input [9:0] ADC_DATA_IN2,
    output ADC_CLK_STB_OUT
  );




/*
  _____ _                   _     
 / ____(_)                 | |    
| (___  _  __ _ _ __   __ _| |___ 
 \___ \| |/ _` | '_ \ / _` | / __|
 ____) | | (_| | | | | (_| | \__ \ 
|_____/|_|\__, |_| |_|\__,_|_|___/
          __/ |                  
         |___/                   
*/
  // bram: accum0_snap/ss/bram
  wire [11:0] accum0_snap_ss_bram_accum0_snap_ss_bram_addr;
  wire [31:0] accum0_snap_ss_bram_accum0_snap_ss_bram_data_in;
  wire [31:0] accum0_snap_ss_bram_accum0_snap_ss_bram_data_out;
  wire [0:0] accum0_snap_ss_bram_accum0_snap_ss_bram_we;
  wire [11:0] test_spec_accum0_snap_ss_bram_addr;
  wire [31:0] test_spec_accum0_snap_ss_bram_data_in;
  wire [31:0] test_spec_accum0_snap_ss_bram_data_out;
  wire [0:0] test_spec_accum0_snap_ss_bram_we;
  // bram: accum1_snap/ss/bram
  wire [11:0] accum1_snap_ss_bram_accum1_snap_ss_bram_addr;
  wire [31:0] accum1_snap_ss_bram_accum1_snap_ss_bram_data_in;
  wire [31:0] accum1_snap_ss_bram_accum1_snap_ss_bram_data_out;
  wire [0:0] accum1_snap_ss_bram_accum1_snap_ss_bram_we;
  wire [11:0] test_spec_accum1_snap_ss_bram_addr;
  wire [31:0] test_spec_accum1_snap_ss_bram_data_in;
  wire [31:0] test_spec_accum1_snap_ss_bram_data_out;
  wire [0:0] test_spec_accum1_snap_ss_bram_we;
  // bram: accumdat_snap/ss/bram
  wire [11:0] accumdat_snap_ss_bram_accumdat_snap_ss_bram_addr;
  wire [31:0] accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_in;
  wire [31:0] accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_out;
  wire [0:0] accumdat_snap_ss_bram_accumdat_snap_ss_bram_we;
  wire [11:0] test_spec_accumdat_snap_ss_bram_addr;
  wire [31:0] test_spec_accumdat_snap_ss_bram_data_in;
  wire [31:0] test_spec_accumdat_snap_ss_bram_data_out;
  wire [0:0] test_spec_accumdat_snap_ss_bram_we;
  // bram: adc_voltage_snap/ss/bram
  wire [11:0] adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_addr;
  wire [31:0] adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_in;
  wire [31:0] adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_out;
  wire [0:0] adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_we;
  wire [11:0] test_spec_adc_voltage_snap_ss_bram_addr;
  wire [31:0] test_spec_adc_voltage_snap_ss_bram_data_in;
  wire [31:0] test_spec_adc_voltage_snap_ss_bram_data_out;
  wire [0:0] test_spec_adc_voltage_snap_ss_bram_we;
  // red_pitaya: RED_PITAYA
  wire [31:0] M_AXI_araddr;
  wire [2:0] M_AXI_arprot;
  wire M_AXI_arready;
  wire M_AXI_arvalid;
  wire [31:0] M_AXI_awaddr;
  wire [2:0] M_AXI_awprot;
  wire M_AXI_awready;
  wire M_AXI_awvalid;
  wire M_AXI_bready;
  wire [1:0] M_AXI_bresp;
  wire M_AXI_bvalid;
  wire [31:0] M_AXI_rdata;
  wire M_AXI_rready;
  wire [1:0] M_AXI_rresp;
  wire M_AXI_rvalid;
  wire [31:0] M_AXI_wdata;
  wire M_AXI_wready;
  wire [3:0] M_AXI_wstrb;
  wire M_AXI_wvalid;
  wire [0:0] adc_clk;
  wire [0:0] adc_clk180;
  wire [0:0] adc_clk270;
  wire [0:0] adc_clk90;
  wire [0:0] adc_rst;
  wire axil_clk;
  wire axil_rst;
  wire axil_rst_n;
  wire [0:0] dac_clk;
  wire [0:0] dac_clk_p;
  wire [0:0] dac_rst;
  wire [0:0] sys_rst;
  // red_pitaya_adc: red_pitaya_adc
  wire [9:0] test_spec_red_pitaya_adc_adc0_data_i_out;
  wire [9:0] test_spec_red_pitaya_adc_adc1_data_q_out;
  wire test_spec_red_pitaya_adc_adc_data_val_out;
  wire test_spec_red_pitaya_adc_adc_reset_in;
  // sw_reg: acc_cnt
  wire [31:0] sw_reg_acc_cnt_in;
  wire [31:0] test_spec_acc_cnt_user_data_in;
  // sw_reg: acc_len
  wire [31:0] sw_reg_acc_len_out;
  wire [31:0] test_spec_acc_len_user_data_out;
  // sw_reg: accum0_snap/ss/ctrl
  wire [31:0] sw_reg_accum0_snap_ss_ctrl_out;
  wire [31:0] test_spec_accum0_snap_ss_ctrl_user_data_out;
  // sw_reg: accum0_snap/ss/status
  wire [31:0] sw_reg_accum0_snap_ss_status_in;
  wire [31:0] test_spec_accum0_snap_ss_status_user_data_in;
  // sw_reg: accum1_snap/ss/ctrl
  wire [31:0] sw_reg_accum1_snap_ss_ctrl_out;
  wire [31:0] test_spec_accum1_snap_ss_ctrl_user_data_out;
  // sw_reg: accum1_snap/ss/status
  wire [31:0] sw_reg_accum1_snap_ss_status_in;
  wire [31:0] test_spec_accum1_snap_ss_status_user_data_in;
  // sw_reg: accumdat_snap/ss/ctrl
  wire [31:0] sw_reg_accumdat_snap_ss_ctrl_out;
  wire [31:0] test_spec_accumdat_snap_ss_ctrl_user_data_out;
  // sw_reg: accumdat_snap/ss/status
  wire [31:0] sw_reg_accumdat_snap_ss_status_in;
  wire [31:0] test_spec_accumdat_snap_ss_status_user_data_in;
  // sw_reg: adc_dv
  wire [31:0] sw_reg_adc_dv_in;
  wire [31:0] test_spec_adc_dv_user_data_in;
  // sw_reg: adc_sample_cnt
  wire [31:0] sw_reg_adc_sample_cnt_in;
  wire [31:0] test_spec_adc_sample_cnt_user_data_in;
  // sw_reg: adc_voltage_snap/ss/ctrl
  wire [31:0] sw_reg_adc_voltage_snap_ss_ctrl_out;
  wire [31:0] test_spec_adc_voltage_snap_ss_ctrl_user_data_out;
  // sw_reg: adc_voltage_snap/ss/status
  wire [31:0] sw_reg_adc_voltage_snap_ss_status_in;
  wire [31:0] test_spec_adc_voltage_snap_ss_status_user_data_in;
  // sw_reg: fft_sync_inc0
  wire [31:0] sw_reg_fft_sync_inc0_in;
  wire [31:0] test_spec_fft_sync_inc0_user_data_in;
  // sw_reg: fft_sync_inc1
  wire [31:0] sw_reg_fft_sync_inc1_in;
  wire [31:0] test_spec_fft_sync_inc1_user_data_in;
  // sw_reg: reg_cntrl
  wire [31:0] sw_reg_reg_cntrl_out;
  wire [31:0] test_spec_reg_cntrl_user_data_out;
  // sw_reg: snap_gap
  wire [31:0] sw_reg_snap_gap_out;
  wire [31:0] test_spec_snap_gap_user_data_out;
  // sw_reg: sync_cnt
  wire [31:0] sw_reg_sync_cnt_in;
  wire [31:0] test_spec_sync_cnt_user_data_in;
  // sys_block: RED_PITAYA
  wire [0:0] sw_reg_acc_cnt_in_we;
  wire [0:0] sw_reg_acc_len_out_we;
  wire [0:0] sw_reg_accum0_snap_ss_ctrl_out_we;
  wire [0:0] sw_reg_accum0_snap_ss_status_in_we;
  wire [0:0] sw_reg_accum1_snap_ss_ctrl_out_we;
  wire [0:0] sw_reg_accum1_snap_ss_status_in_we;
  wire [0:0] sw_reg_accumdat_snap_ss_ctrl_out_we;
  wire [0:0] sw_reg_accumdat_snap_ss_status_in_we;
  wire [0:0] sw_reg_adc_dv_in_we;
  wire [0:0] sw_reg_adc_sample_cnt_in_we;
  wire [0:0] sw_reg_adc_voltage_snap_ss_ctrl_out_we;
  wire [0:0] sw_reg_adc_voltage_snap_ss_status_in_we;
  wire [0:0] sw_reg_fft_sync_inc0_in_we;
  wire [0:0] sw_reg_fft_sync_inc1_in_we;
  wire [0:0] sw_reg_reg_cntrl_out_we;
  wire [0:0] sw_reg_snap_gap_out_we;
  wire [0:0] sw_reg_sync_cnt_in_we;
  wire [31:0] sys_board_id_in;
  wire [0:0] sys_board_id_in_we;
  wire [31:0] sys_clkcounter_cdc;
  wire [31:0] sys_clkcounter_in;
  wire [0:0] sys_clkcounter_in_we;
  wire [0:0] sys_clkcounter_we;
  wire [31:0] sys_rev_in;
  wire [0:0] sys_rev_in_we;
  wire [31:0] sys_rev_rcs_in;
  wire [0:0] sys_rev_rcs_in_we;
  wire [31:0] sys_scratchpad_out;
  wire [0:0] sys_scratchpad_out_we;
  wire user_rst;
  // xsg: RED_PITAYA
  (* keep = "true" *) wire sys_clk;
  (* keep = "true" *) wire user_clk;
  (* keep = "true" *) wire user_clk180;
  (* keep = "true" *) wire user_clk270;
  (* keep = "true" *) wire user_clk90;

/*
  _____           _                            
 |_   _|         | |                           
   | |  _ __  ___| |_ __ _ _ __   ___ ___  ___ 
   | | | '_ \/ __| __/ _` | '_ \ / __/ _ \/ __|
  _| |_| | | \__ \ || (_| | | | | (_|  __/\__ \ 
 |_____|_| |_|___/\__\__,_|_| |_|\___\___||___/
*/
  // red_pitaya: RED_PITAYA
  red_pitaya_bd  red_pitaya_bd_inst (
    .DDR_Addr(DDR_Addr),
    .DDR_CAS_n(DDR_CAS_n),
    .DDR_CKE(DDR_CKE),
    .DDR_CS_n(DDR_CS_n),
    .DDR_Ck_n(DDR_Ck_n),
    .DDR_Ck_p(DDR_Ck_p),
    .DDR_DM(DDR_DM),
    .DDR_DQ(DDR_DQ),
    .DDR_DQS_n(DDR_DQS_n),
    .DDR_DQS_p(DDR_DQS_p),
    .DDR_ODT(DDR_ODT),
    .DDR_RAS_n(DDR_RAS_n),
    .DDR_ba(DDR_ba),
    .DDR_reset_n(DDR_reset_n),
    .DDR_we_n(DDR_we_n),
    .FIXED_IO_ddr_vrn(FIXED_IO_ddr_vrn),
    .FIXED_IO_ddr_vrp(FIXED_IO_ddr_vrp),
    .FIXED_IO_ps_clk(FIXED_IO_ps_clk),
    .FIXED_IO_ps_porb(FIXED_IO_ps_porb),
    .FIXED_IO_ps_srstb(FIXED_IO_ps_srstb),
    .M_AXI_araddr(M_AXI_araddr),
    .M_AXI_arprot(M_AXI_arprot),
    .M_AXI_arready(M_AXI_arready),
    .M_AXI_arvalid(M_AXI_arvalid),
    .M_AXI_awaddr(M_AXI_awaddr),
    .M_AXI_awprot(M_AXI_awprot),
    .M_AXI_awready(M_AXI_awready),
    .M_AXI_awvalid(M_AXI_awvalid),
    .M_AXI_bready(M_AXI_bready),
    .M_AXI_bresp(M_AXI_bresp),
    .M_AXI_bvalid(M_AXI_bvalid),
    .M_AXI_rdata(M_AXI_rdata),
    .M_AXI_rready(M_AXI_rready),
    .M_AXI_rresp(M_AXI_rresp),
    .M_AXI_rvalid(M_AXI_rvalid),
    .M_AXI_wdata(M_AXI_wdata),
    .M_AXI_wready(M_AXI_wready),
    .M_AXI_wstrb(M_AXI_wstrb),
    .M_AXI_wvalid(M_AXI_wvalid),
    .axil_clk(axil_clk),
    .axil_rst(axil_rst),
    .axil_rst_n(axil_rst_n)
  );


  red_pitaya_infrastructure #(
    .DIVCLK(1),
    .DIVIDE(8.0),
    .MULTIPLY(8.0)
  ) red_pitaya_infr_inst (
    .adc_clk_125(adc_clk),
    .adc_clk_in(ADC_CLK_IN_P),
    .adc_clk_p180(adc_clk180),
    .adc_clk_p270(adc_clk270),
    .adc_clk_p90(adc_clk90),
    .adc_rst(adc_rst),
    .dac_clk_250(dac_clk),
    .dac_clk_250_p315(dac_clk_p),
    .dac_rst(dac_rst),
    .dsp_clk(sys_clk),
    .dsp_clk_p180(sys_clk180),
    .dsp_clk_p270(sys_clk270),
    .dsp_clk_p90(sys_clk90),
    .dsp_rst(sys_rst)
  );

  // red_pitaya_adc: red_pitaya_adc
  // test_spec_red_pitaya_adc
  red_pitaya_adc #(
    .NUM_OF_BITS(10)
  ) test_spec_red_pitaya_adc (
    .ADC0_DATA_I_OUT(test_spec_red_pitaya_adc_adc0_data_i_out),
    .ADC1_DATA_Q_OUT(test_spec_red_pitaya_adc_adc1_data_q_out),
    .ADC_CLK_IN(adc_clk),
    .ADC_CLK_STB_OUT(ADC_CLK_STB_OUT),
    .ADC_DATA_IN1(ADC_DATA_IN1),
    .ADC_DATA_IN2(ADC_DATA_IN2),
    .ADC_DATA_VAL_OUT(test_spec_red_pitaya_adc_adc_data_val_out),
    .ADC_RST_IN(test_spec_red_pitaya_adc_adc_reset_in),
    .ADC_RST_IN2(adc_rst),
    .DSP_CLK_IN(user_clk),
    .DSP_RST_IN(user_rst)
  );

  // sw_reg: acc_cnt
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_acc_cnt (
    .IP_BUS(test_spec_acc_cnt_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_acc_cnt_in)
  );

  // sw_reg: acc_len
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h2)
  ) test_spec_acc_len (
    .IP_BUS(sw_reg_acc_len_out),
    .IP_BUS_VALID(sw_reg_acc_len_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_acc_len_user_data_out)
  );

  // sw_reg: accum0_snap/ss/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) test_spec_accum0_snap_ss_ctrl (
    .IP_BUS(sw_reg_accum0_snap_ss_ctrl_out),
    .IP_BUS_VALID(sw_reg_accum0_snap_ss_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_accum0_snap_ss_ctrl_user_data_out)
  );

  // sw_reg: accum0_snap/ss/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_accum0_snap_ss_status (
    .IP_BUS(test_spec_accum0_snap_ss_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_accum0_snap_ss_status_in)
  );

  // sw_reg: accum1_snap/ss/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) test_spec_accum1_snap_ss_ctrl (
    .IP_BUS(sw_reg_accum1_snap_ss_ctrl_out),
    .IP_BUS_VALID(sw_reg_accum1_snap_ss_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_accum1_snap_ss_ctrl_user_data_out)
  );

  // sw_reg: accum1_snap/ss/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_accum1_snap_ss_status (
    .IP_BUS(test_spec_accum1_snap_ss_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_accum1_snap_ss_status_in)
  );

  // sw_reg: accumdat_snap/ss/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) test_spec_accumdat_snap_ss_ctrl (
    .IP_BUS(sw_reg_accumdat_snap_ss_ctrl_out),
    .IP_BUS_VALID(sw_reg_accumdat_snap_ss_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_accumdat_snap_ss_ctrl_user_data_out)
  );

  // sw_reg: accumdat_snap/ss/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_accumdat_snap_ss_status (
    .IP_BUS(test_spec_accumdat_snap_ss_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_accumdat_snap_ss_status_in)
  );

  // sw_reg: adc_dv
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_adc_dv (
    .IP_BUS(test_spec_adc_dv_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_adc_dv_in)
  );

  // sw_reg: adc_sample_cnt
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_adc_sample_cnt (
    .IP_BUS(test_spec_adc_sample_cnt_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_adc_sample_cnt_in)
  );

  // sw_reg: adc_voltage_snap/ss/ctrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) test_spec_adc_voltage_snap_ss_ctrl (
    .IP_BUS(sw_reg_adc_voltage_snap_ss_ctrl_out),
    .IP_BUS_VALID(sw_reg_adc_voltage_snap_ss_ctrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_adc_voltage_snap_ss_ctrl_user_data_out)
  );

  // sw_reg: adc_voltage_snap/ss/status
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_adc_voltage_snap_ss_status (
    .IP_BUS(test_spec_adc_voltage_snap_ss_status_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_adc_voltage_snap_ss_status_in)
  );

  // sw_reg: fft_sync_inc0
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_fft_sync_inc0 (
    .IP_BUS(test_spec_fft_sync_inc0_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_fft_sync_inc0_in)
  );

  // sw_reg: fft_sync_inc1
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_fft_sync_inc1 (
    .IP_BUS(test_spec_fft_sync_inc1_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_fft_sync_inc1_in)
  );

  // sw_reg: reg_cntrl
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h0)
  ) test_spec_reg_cntrl (
    .IP_BUS(sw_reg_reg_cntrl_out),
    .IP_BUS_VALID(sw_reg_reg_cntrl_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_reg_cntrl_user_data_out)
  );

  // sw_reg: snap_gap
  cdc_synchroniser #(
    .G_BUS_WIDTH(32),
    .G_OP_INITIAL_VAL(32'h14)
  ) test_spec_snap_gap (
    .IP_BUS(sw_reg_snap_gap_out),
    .IP_BUS_VALID(sw_reg_snap_gap_out_we),
    .IP_CLK(user_clk),
    .IP_RESET(user_rst),
    .OP_BUS(test_spec_snap_gap_user_data_out)
  );

  // sw_reg: sync_cnt
  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) test_spec_sync_cnt (
    .IP_BUS(test_spec_sync_cnt_user_data_in),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sw_reg_sync_cnt_in)
  );

  // sys_block: RED_PITAYA
  axi4lite_ic_wrapper  axi4lite_interconnect (
    .axi4lite_accum0_snap_ss_bram_accum0_snap_ss_bram_add(accum0_snap_ss_bram_accum0_snap_ss_bram_addr),
    .axi4lite_accum0_snap_ss_bram_accum0_snap_ss_bram_clk(user_clk),
    .axi4lite_accum0_snap_ss_bram_accum0_snap_ss_bram_data_in(accum0_snap_ss_bram_accum0_snap_ss_bram_data_in),
    .axi4lite_accum0_snap_ss_bram_accum0_snap_ss_bram_data_out(accum0_snap_ss_bram_accum0_snap_ss_bram_data_out),
    .axi4lite_accum0_snap_ss_bram_accum0_snap_ss_bram_en(1'b1),
    .axi4lite_accum0_snap_ss_bram_accum0_snap_ss_bram_we(accum0_snap_ss_bram_accum0_snap_ss_bram_we),
    .axi4lite_accum1_snap_ss_bram_accum1_snap_ss_bram_add(accum1_snap_ss_bram_accum1_snap_ss_bram_addr),
    .axi4lite_accum1_snap_ss_bram_accum1_snap_ss_bram_clk(user_clk),
    .axi4lite_accum1_snap_ss_bram_accum1_snap_ss_bram_data_in(accum1_snap_ss_bram_accum1_snap_ss_bram_data_in),
    .axi4lite_accum1_snap_ss_bram_accum1_snap_ss_bram_data_out(accum1_snap_ss_bram_accum1_snap_ss_bram_data_out),
    .axi4lite_accum1_snap_ss_bram_accum1_snap_ss_bram_en(1'b1),
    .axi4lite_accum1_snap_ss_bram_accum1_snap_ss_bram_we(accum1_snap_ss_bram_accum1_snap_ss_bram_we),
    .axi4lite_accumdat_snap_ss_bram_accumdat_snap_ss_bram_add(accumdat_snap_ss_bram_accumdat_snap_ss_bram_addr),
    .axi4lite_accumdat_snap_ss_bram_accumdat_snap_ss_bram_clk(user_clk),
    .axi4lite_accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_in(accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_in),
    .axi4lite_accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_out(accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_out),
    .axi4lite_accumdat_snap_ss_bram_accumdat_snap_ss_bram_en(1'b1),
    .axi4lite_accumdat_snap_ss_bram_accumdat_snap_ss_bram_we(accumdat_snap_ss_bram_accumdat_snap_ss_bram_we),
    .axi4lite_aclk(axil_clk),
    .axi4lite_adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_add(adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_addr),
    .axi4lite_adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_clk(user_clk),
    .axi4lite_adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_in(adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_in),
    .axi4lite_adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_out(adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_out),
    .axi4lite_adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_en(1'b1),
    .axi4lite_adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_we(adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_we),
    .axi4lite_aresetn(axil_rst_n),
    .axi4lite_sw_reg_acc_cnt_in(sw_reg_acc_cnt_in),
    .axi4lite_sw_reg_acc_cnt_in_we(sw_reg_acc_cnt_in_we),
    .axi4lite_sw_reg_acc_len_out(sw_reg_acc_len_out),
    .axi4lite_sw_reg_acc_len_out_we(sw_reg_acc_len_out_we),
    .axi4lite_sw_reg_accum0_snap_ss_ctrl_out(sw_reg_accum0_snap_ss_ctrl_out),
    .axi4lite_sw_reg_accum0_snap_ss_ctrl_out_we(sw_reg_accum0_snap_ss_ctrl_out_we),
    .axi4lite_sw_reg_accum0_snap_ss_status_in(sw_reg_accum0_snap_ss_status_in),
    .axi4lite_sw_reg_accum0_snap_ss_status_in_we(sw_reg_accum0_snap_ss_status_in_we),
    .axi4lite_sw_reg_accum1_snap_ss_ctrl_out(sw_reg_accum1_snap_ss_ctrl_out),
    .axi4lite_sw_reg_accum1_snap_ss_ctrl_out_we(sw_reg_accum1_snap_ss_ctrl_out_we),
    .axi4lite_sw_reg_accum1_snap_ss_status_in(sw_reg_accum1_snap_ss_status_in),
    .axi4lite_sw_reg_accum1_snap_ss_status_in_we(sw_reg_accum1_snap_ss_status_in_we),
    .axi4lite_sw_reg_accumdat_snap_ss_ctrl_out(sw_reg_accumdat_snap_ss_ctrl_out),
    .axi4lite_sw_reg_accumdat_snap_ss_ctrl_out_we(sw_reg_accumdat_snap_ss_ctrl_out_we),
    .axi4lite_sw_reg_accumdat_snap_ss_status_in(sw_reg_accumdat_snap_ss_status_in),
    .axi4lite_sw_reg_accumdat_snap_ss_status_in_we(sw_reg_accumdat_snap_ss_status_in_we),
    .axi4lite_sw_reg_adc_dv_in(sw_reg_adc_dv_in),
    .axi4lite_sw_reg_adc_dv_in_we(sw_reg_adc_dv_in_we),
    .axi4lite_sw_reg_adc_sample_cnt_in(sw_reg_adc_sample_cnt_in),
    .axi4lite_sw_reg_adc_sample_cnt_in_we(sw_reg_adc_sample_cnt_in_we),
    .axi4lite_sw_reg_adc_voltage_snap_ss_ctrl_out(sw_reg_adc_voltage_snap_ss_ctrl_out),
    .axi4lite_sw_reg_adc_voltage_snap_ss_ctrl_out_we(sw_reg_adc_voltage_snap_ss_ctrl_out_we),
    .axi4lite_sw_reg_adc_voltage_snap_ss_status_in(sw_reg_adc_voltage_snap_ss_status_in),
    .axi4lite_sw_reg_adc_voltage_snap_ss_status_in_we(sw_reg_adc_voltage_snap_ss_status_in_we),
    .axi4lite_sw_reg_fft_sync_inc0_in(sw_reg_fft_sync_inc0_in),
    .axi4lite_sw_reg_fft_sync_inc0_in_we(sw_reg_fft_sync_inc0_in_we),
    .axi4lite_sw_reg_fft_sync_inc1_in(sw_reg_fft_sync_inc1_in),
    .axi4lite_sw_reg_fft_sync_inc1_in_we(sw_reg_fft_sync_inc1_in_we),
    .axi4lite_sw_reg_reg_cntrl_out(sw_reg_reg_cntrl_out),
    .axi4lite_sw_reg_reg_cntrl_out_we(sw_reg_reg_cntrl_out_we),
    .axi4lite_sw_reg_snap_gap_out(sw_reg_snap_gap_out),
    .axi4lite_sw_reg_snap_gap_out_we(sw_reg_snap_gap_out_we),
    .axi4lite_sw_reg_sync_cnt_in(sw_reg_sync_cnt_in),
    .axi4lite_sw_reg_sync_cnt_in_we(sw_reg_sync_cnt_in_we),
    .axi4lite_sys_board_id_in(sys_board_id_in),
    .axi4lite_sys_board_id_in_we(sys_board_id_in_we),
    .axi4lite_sys_clkcounter_in(sys_clkcounter_in),
    .axi4lite_sys_clkcounter_in_we(sys_clkcounter_in_we),
    .axi4lite_sys_rev_in(sys_rev_in),
    .axi4lite_sys_rev_in_we(sys_rev_in_we),
    .axi4lite_sys_rev_rcs_in(sys_rev_rcs_in),
    .axi4lite_sys_rev_rcs_in_we(sys_rev_rcs_in_we),
    .axi4lite_sys_scratchpad_out(sys_scratchpad_out),
    .axi4lite_sys_scratchpad_out_we(sys_scratchpad_out_we),
    .s_axi4lite_araddr(M_AXI_araddr),
    .s_axi4lite_arready(M_AXI_arready),
    .s_axi4lite_arvalid(M_AXI_arvalid),
    .s_axi4lite_awaddr(M_AXI_awaddr),
    .s_axi4lite_awready(M_AXI_awready),
    .s_axi4lite_awvalid(M_AXI_awvalid),
    .s_axi4lite_bready(M_AXI_bready),
    .s_axi4lite_bresp(M_AXI_bresp),
    .s_axi4lite_bvalid(M_AXI_bvalid),
    .s_axi4lite_rdata(M_AXI_rdata),
    .s_axi4lite_rready(M_AXI_rready),
    .s_axi4lite_rresp(M_AXI_rresp),
    .s_axi4lite_rvalid(M_AXI_rvalid),
    .s_axi4lite_wdata(M_AXI_wdata),
    .s_axi4lite_wready(M_AXI_wready),
    .s_axi4lite_wstrb(M_AXI_wstrb),
    .s_axi4lite_wvalid(M_AXI_wvalid)
  );


  cdc_synchroniser #(
    .G_BUS_WIDTH(32)
  ) sys_block_counter_cdc_inst (
    .IP_BUS(sys_clkcounter_cdc),
    .IP_BUS_VALID(1'b1),
    .IP_CLK(axil_clk),
    .IP_RESET(axil_rst),
    .OP_BUS(sys_clkcounter_in)
  );


  sys_block_counter #(
    .DATA_WIDTH(32)
  ) sys_block_counter_inst (
    .count_out(sys_clkcounter_cdc),
    .en(1),
    .user_clk(user_clk),
    .user_rst(user_rst),
    .we(sys_clkcounter_we)
  );


  test_spec_ip  test_spec_ip_inst (
    .clk(user_clk),
    .test_spec_acc_cnt_user_data_in(test_spec_acc_cnt_user_data_in),
    .test_spec_acc_len_user_data_out(test_spec_acc_len_user_data_out),
    .test_spec_accum0_snap_ss_bram_addr(test_spec_accum0_snap_ss_bram_addr),
    .test_spec_accum0_snap_ss_bram_data_in(test_spec_accum0_snap_ss_bram_data_in),
    .test_spec_accum0_snap_ss_bram_data_out(test_spec_accum0_snap_ss_bram_data_out),
    .test_spec_accum0_snap_ss_bram_we(test_spec_accum0_snap_ss_bram_we),
    .test_spec_accum0_snap_ss_ctrl_user_data_out(test_spec_accum0_snap_ss_ctrl_user_data_out),
    .test_spec_accum0_snap_ss_status_user_data_in(test_spec_accum0_snap_ss_status_user_data_in),
    .test_spec_accum1_snap_ss_bram_addr(test_spec_accum1_snap_ss_bram_addr),
    .test_spec_accum1_snap_ss_bram_data_in(test_spec_accum1_snap_ss_bram_data_in),
    .test_spec_accum1_snap_ss_bram_data_out(test_spec_accum1_snap_ss_bram_data_out),
    .test_spec_accum1_snap_ss_bram_we(test_spec_accum1_snap_ss_bram_we),
    .test_spec_accum1_snap_ss_ctrl_user_data_out(test_spec_accum1_snap_ss_ctrl_user_data_out),
    .test_spec_accum1_snap_ss_status_user_data_in(test_spec_accum1_snap_ss_status_user_data_in),
    .test_spec_accumdat_snap_ss_bram_addr(test_spec_accumdat_snap_ss_bram_addr),
    .test_spec_accumdat_snap_ss_bram_data_in(test_spec_accumdat_snap_ss_bram_data_in),
    .test_spec_accumdat_snap_ss_bram_data_out(test_spec_accumdat_snap_ss_bram_data_out),
    .test_spec_accumdat_snap_ss_bram_we(test_spec_accumdat_snap_ss_bram_we),
    .test_spec_accumdat_snap_ss_ctrl_user_data_out(test_spec_accumdat_snap_ss_ctrl_user_data_out),
    .test_spec_accumdat_snap_ss_status_user_data_in(test_spec_accumdat_snap_ss_status_user_data_in),
    .test_spec_adc_dv_user_data_in(test_spec_adc_dv_user_data_in),
    .test_spec_adc_sample_cnt_user_data_in(test_spec_adc_sample_cnt_user_data_in),
    .test_spec_adc_voltage_snap_ss_bram_addr(test_spec_adc_voltage_snap_ss_bram_addr),
    .test_spec_adc_voltage_snap_ss_bram_data_in(test_spec_adc_voltage_snap_ss_bram_data_in),
    .test_spec_adc_voltage_snap_ss_bram_data_out(test_spec_adc_voltage_snap_ss_bram_data_out),
    .test_spec_adc_voltage_snap_ss_bram_we(test_spec_adc_voltage_snap_ss_bram_we),
    .test_spec_adc_voltage_snap_ss_ctrl_user_data_out(test_spec_adc_voltage_snap_ss_ctrl_user_data_out),
    .test_spec_adc_voltage_snap_ss_status_user_data_in(test_spec_adc_voltage_snap_ss_status_user_data_in),
    .test_spec_fft_sync_inc0_user_data_in(test_spec_fft_sync_inc0_user_data_in),
    .test_spec_fft_sync_inc1_user_data_in(test_spec_fft_sync_inc1_user_data_in),
    .test_spec_red_pitaya_adc_adc0_data_i_out(test_spec_red_pitaya_adc_adc0_data_i_out),
    .test_spec_red_pitaya_adc_adc1_data_q_out(test_spec_red_pitaya_adc_adc1_data_q_out),
    .test_spec_red_pitaya_adc_adc_data_val_out(test_spec_red_pitaya_adc_adc_data_val_out),
    .test_spec_red_pitaya_adc_adc_reset_in(test_spec_red_pitaya_adc_adc_reset_in),
    .test_spec_reg_cntrl_user_data_out(test_spec_reg_cntrl_user_data_out),
    .test_spec_snap_gap_user_data_out(test_spec_snap_gap_user_data_out),
    .test_spec_sync_cnt_user_data_in(test_spec_sync_cnt_user_data_in)
  );


/*
                   _                                  _       
     /\           (_)                                | |      
    /  \   ___ ___ _  __ _ _ __  _ __ ___   ___ _ __ | |_ ___ 
   / /\ \ / __/ __| |/ _` | '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
  / ____ \\__ \__ \ | (_| | | | | | | | | |  __/ | | | |_\__ \ 
 /_/    \_\___/___/_|\__, |_| |_|_| |_| |_|\___|_| |_|\__|___/
                      __/ |                                   
                     |___/                                    
*/
  // bram: accum0_snap/ss/bram
  assign accum0_snap_ss_bram_accum0_snap_ss_bram_addr = test_spec_accum0_snap_ss_bram_addr;
  assign accum0_snap_ss_bram_accum0_snap_ss_bram_data_in = test_spec_accum0_snap_ss_bram_data_in;
  assign accum0_snap_ss_bram_accum0_snap_ss_bram_data_out = test_spec_accum0_snap_ss_bram_data_out;
  assign accum0_snap_ss_bram_accum0_snap_ss_bram_we = test_spec_accum0_snap_ss_bram_we;
  // bram: accum1_snap/ss/bram
  assign accum1_snap_ss_bram_accum1_snap_ss_bram_addr = test_spec_accum1_snap_ss_bram_addr;
  assign accum1_snap_ss_bram_accum1_snap_ss_bram_data_in = test_spec_accum1_snap_ss_bram_data_in;
  assign accum1_snap_ss_bram_accum1_snap_ss_bram_data_out = test_spec_accum1_snap_ss_bram_data_out;
  assign accum1_snap_ss_bram_accum1_snap_ss_bram_we = test_spec_accum1_snap_ss_bram_we;
  // bram: accumdat_snap/ss/bram
  assign accumdat_snap_ss_bram_accumdat_snap_ss_bram_addr = test_spec_accumdat_snap_ss_bram_addr;
  assign accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_in = test_spec_accumdat_snap_ss_bram_data_in;
  assign accumdat_snap_ss_bram_accumdat_snap_ss_bram_data_out = test_spec_accumdat_snap_ss_bram_data_out;
  assign accumdat_snap_ss_bram_accumdat_snap_ss_bram_we = test_spec_accumdat_snap_ss_bram_we;
  // bram: adc_voltage_snap/ss/bram
  assign adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_addr = test_spec_adc_voltage_snap_ss_bram_addr;
  assign adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_in = test_spec_adc_voltage_snap_ss_bram_data_in;
  assign adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_data_out = test_spec_adc_voltage_snap_ss_bram_data_out;
  assign adc_voltage_snap_ss_bram_adc_voltage_snap_ss_bram_we = test_spec_adc_voltage_snap_ss_bram_we;
  // xsg: RED_PITAYA
  assign user_clk = sys_clk;
  assign user_clk180 = sys_clk180;
  assign user_clk270 = sys_clk270;
  assign user_clk90 = sys_clk90;


endmodule