# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/ip/test_spec_ip/test_spec_ip.xci
# IP: The module: 'test_spec_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_addsub_v12_0_i0/test_spec_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_addsub_v12_0_i0 || ORIG_REF_NAME==test_spec_c_addsub_v12_0_i0} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i0/test_spec_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i1/test_spec_c_counter_binary_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i2/test_spec_c_counter_binary_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i2} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i3/test_spec_c_counter_binary_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i3} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i4/test_spec_c_counter_binary_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i4} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i5/test_spec_c_counter_binary_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i5} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i6/test_spec_c_counter_binary_v12_0_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i6 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i6} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_mult_gen_v12_0_i0/test_spec_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_mult_gen_v12_0_i0 || ORIG_REF_NAME==test_spec_mult_gen_v12_0_i0} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_xfft_v9_1_i0/test_spec_xfft_v9_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_xfft_v9_1_i0 || ORIG_REF_NAME==test_spec_xfft_v9_1_i0} -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/constrs/test_spec.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_spec_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/ip/test_spec_ip/test_spec_ip.xci
# IP: The module: 'test_spec_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_addsub_v12_0_i0/test_spec_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_addsub_v12_0_i0 || ORIG_REF_NAME==test_spec_c_addsub_v12_0_i0} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i0/test_spec_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i1/test_spec_c_counter_binary_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i1} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i2/test_spec_c_counter_binary_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i2} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i3/test_spec_c_counter_binary_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i3} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i4/test_spec_c_counter_binary_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i4} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i5/test_spec_c_counter_binary_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i5} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_c_counter_binary_v12_0_i6/test_spec_c_counter_binary_v12_0_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_c_counter_binary_v12_0_i6 || ORIG_REF_NAME==test_spec_c_counter_binary_v12_0_i6} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_mult_gen_v12_0_i0/test_spec_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_mult_gen_v12_0_i0 || ORIG_REF_NAME==test_spec_mult_gen_v12_0_i0} -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/test_spec_xfft_v9_1_i0/test_spec_xfft_v9_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_spec_xfft_v9_1_i0 || ORIG_REF_NAME==test_spec_xfft_v9_1_i0} -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/ip/test_spec_ip/constrs/test_spec.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_spec_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
