# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0.xci
# IP: The module: 'red_pitaya_bd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.srcs/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0.xci
# IP: The module: 'red_pitaya_bd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/shishir/pythontest/Red-Pitaya-Casper-Toolflow/red_pitaya/test_spec/test_spec/myproj/myproj.gen/sources_1/bd/red_pitaya_bd/ip/red_pitaya_bd_rst_ps7_0_50M_0/red_pitaya_bd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'red_pitaya_bd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
